import { GiWoodenChair, GiWoodenSign, GiWoodenDoor, GiWoodenCrate, 
    GiBed, GiLabradorHead, GiLaptop, GiLemon, GiLindenLeaf, GiLockedChest, GiLyre,
    GiLongLeggedSpider, GiLorgnette, GiLoveSong, GiLadder } from "react-icons/gi";
import {TbLamp} from "react-icons/tb"

let listOfIcons =[
    {id:1,
    icon:GiWoodenChair,
    correct:true}, 
    {id:2,
    icon:GiWoodenSign,
    correct:false}, 
    {id:3,
    icon:GiWoodenDoor,
    correct:false}, 
    {id:4,
    icon:GiWoodenCrate,
    correct:false},
    {id:5,
    icon:TbLamp,
    correct:true}, 
    {id:6,
    icon:GiBed,
    correct:false}, 
    {id:7,
    icon:GiLabradorHead,
    correct:false},
    {id:8, 
    icon:GiLaptop,
    correct:false}, 
    {id:9,
    icon:GiLemon,
    correct:false}, 
    {id:10,
    icon:GiLindenLeaf,
    correct:false},
    {id:11,
    icon:GiLockedChest,
    correct:false},
    {id:12,
    icon:GiLyre,
    correct:false},
    {id:13,
    icon:GiLongLeggedSpider,
    correct:false},
    {id:14,
    icon:GiLorgnette,
    correct:false}, 
    {id:15,
    icon:GiLoveSong,
    correct:false},
    {id:16,
    icon:GiLadder,
    correct:false}];

    export default listOfIcons